<?xml version="1.0"?>
<package format="3">
  <name>htn_control</name>
  <version>0.0.1</version>
  <description>Manual teleop of the exoskeleton hand fingers</description>
  <maintainer email="zechariahwang@gmail.com">zech</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
